name: Docker Image CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses : 'actions/checkout@v2'
    - name: Build the Docker image
      run: docker build -t docker-react -f Dockerfile.dev .

    - name: running a docker image
      run: docker run docker-react npm run test -- --watchAll=false
